config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'contact', to: 'welcome#contact'
  get 'meeting', to: 'welcome#meeting'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
  def meeting
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous">
</script>


<!-- Footer -->
<footer class="page-footer font-small indigo">
  <div class="container">
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">About us</a>
        </h6>
      </div>
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Awards</a>
        </h6>
      </div>
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Help</a>
        </h6>
      </div>
    </div>
    <hr class="rgba-white-light" style="margin: 0 15%;">
    <br>
    <div class="container" style = "padding: 10px;">
      <h2 class="h1">Contact Us</h2>
      <br>
      <div id="map-container-google-1" class="z-depth-1-half map-container" style="height: 300px">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d230.78781984522175!2d73.2108450507681!3d22.255056523638732!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395fc44b5075f95d%3A0x3a94e5f26c3fc368!2sGanga%20Sagar%20Complex!5e0!3m2!1sen!2sin!4v1598789110689!5m2!1sen!2sin" width="400" height="250" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
      </div>

      <table>
        <tr>
          <th>Mobile: </th>
          <td>9376225507</td>
        </tr>
        <tr>
          <th>Email: </th>
          <td>phd1818@gmail.com, pooravd@yahoo.co.in</td>
        </tr>
        <tr>
          <th>Address: &nbsp</th>
          <td>
              Address: 35, Gangasagar Complex (C-Tower), Nr. Ankruti Hospital, Susen-Tarsali Road, Vadodara, Pin 390009
          </td>
        </tr>
      </table>


    </div>
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
      <div class="col-md-8 col-12 mt-5">
      </div>
    </div>
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
    <div class="row pb-3">
      <div class="col-md-12">
        <div class="mb-5 flex-center text-center">
        <ul class = "linkicons" style = "  display: flex !important;
          position: absolute !important;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);">
          <li class = "dli">
            <a href="#">
              <i class="fab fa-facebook-f icon dicon"></i>    </a>
          </li>
          <li class = "dli">
            <a href="#"><i class="fab fa-twitter icon dicon"></i></a>
          </li>
          <li class="dli">
            <a href="#"><i class="fab fa-linkedin-in icon dicon"></i></a></li>
          <li class="dli">
            <a href="#"><i class="fab fa-instagram icon dicon"></i></a></li>
        </ul>
        </div>
      </div>
    </div>
  </div>
  <br><br>
  <div class="footer-copyright text-center py-3" style = "background: black; border-top: white dashed 5px">© 2020 Copyright: DeSinister</div>
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
  <span class="menu_toggle">
    <i class="menu_open fa fa-bars fa-lg"></i>
    <i class="menu_close fa fa-times fa-lg"></i>
  </span>

  <ul class="menu_items">
    <li>
      <%=link_to root_path do%>
        <i class="icon fa fa-home fa-2x"></i> Home
      <%end%>
    </li>
    <li>
      <%=link_to contact_path do%>
        <i class="icon fa fa-address-book fa-2x"></i> Contact Us
      <%end%>
    </li>
    <li>
      <%=link_to meeting_path do%>
        <i class="icon fa fa-coffee fa-2x"></i> Book a Meeting
      <%end%>
    </li>

  </ul>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript">
  // elements
  var page = $('.page');

  $('.menu_toggle').on('click', function(){
    page.toggleClass('shazam');
  });
  $('.content').on('click', function(){
    page.removeClass('shazam');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeocare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@600&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
    <%=render partial: 'layouts/navbar'%>
       <main class="content">
         <div class="content_inner">
           <%= yield %>
           <%=render partial: 'layouts/footer'%>
         </div>
      </main>
    </div>
  </body>
</html>

app/views/welcome/contact.html.erb
CONTACT US

app/views/welcome/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous">
</script>

<div class="full-width parallax1 px-o container-fluid page0">
  <!-- Jumbotron -->
  <div class="jumbotron text-center container">

    <!-- Title -->
    <h1 class="card-title h1 pb-2">Poojan Homeo-Care</h1>

    <!-- Card image -->
    <div class="view overlay my-4">
      <img src="" class="img-fluid" alt="" height="600" width="800">
      <a href="#">
        <div class="mask rgba-white-slight"></div>
      </a>
    </div>


    <div class="container">
      <p class="card-text">
        " Homeopathy cures a greater percentage of cases than any other method of treatment. Homeopathy is the latest and refined method of treating patients economically and non-violently. "
      </p>
      <h4 class="indigo-text h3 mb-4">  ~ Mahatma Gandhi</h4>
    </div>

  </div>
  <!-- Jumbotron -->
</div>
<div class="parallax1"></div>


<!-- HTML Setup -->
<section>
<h1 align = "center", class="h1", style="color: white"> Services Offered: </h1>
  <br>
	<!-- cards::before -->
	<div class="container">

		<div class="row">
			<div class="col-lg-12">
				<div class="row card-animate">
					<div class="col-4-lg col-6-md col-12-sm sp">
						<div class="card border">
							<div class="card-body">
								<div class="card-title">
									Card Title 1
								</div>
								<p class="card-text">Card Body</p>
							</div>
						</div>
					</div>
					<div class="col-4-lg col-6-md col-12-sm sp">
						<div class="card border">
							<div class="card-body">
								<div class="card-title">
									Card Title 2
								</div>
								<p class="card-text">Card Body</p>
							</div>
						</div>
					</div>
					<div class="col-4-lg col-6-md col-12-sm sp">
						<div class="card border">
							<div class="card-body">
								<div class="card-title">
									Card Title 3
								</div>
								<p class="card-text">Card Body</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
  <br>
</section>



<div class="how">
  <h1 class="h1"> How To Use</h1>

</div>

app/views/welcome/meeting.html.erb
MEETING PAGE